[project]
name = "ai-agentg"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "google-genai>=2.25.0",
    "openai==2.44.0",
    "python-dotenv==1.1.0",
    "streamlit>=1.64.0",
]
[project.scripts]
run-agent = "core.main:main"


[tool.setuptools]
packages = ["core", "functions", "ui", "shema"]